#!/bin/sh -ex

# turn off root-login by default
sed -i 's/^PermitRootLogin.*/PermitRootLogin no/' $CHROOT/etc/ssh/sshd_config

# add node14 to apt-get repos
curl -sL https://deb.nodesource.com/setup_14.x | bash -
apt-get -y install nodejs

# add java17
wget https://github.com/AdoptOpenJDK/openjdk17-binaries/releases/download/jdk-2021-05-07-13-31/OpenJDK-jdk_x64_linux_hotspot_2021-05-06-23-30.tar.gz -O openjdk-17-jre.tgz
tar xf openjdk-17-jre.tgz
mv jdk-17* /opt/openjdk-17.0-jre
ln -s /opt/openjdk-17.0-jre/bin/java /usr/bin/java
rm openjdk-17-jre.tgz

# install webui from git
cd /usr/games
git clone --depth=1 https://github.com/hexparrot/mineos-node minecraft
cd minecraft
git config core.filemode false
chmod +x generate-sslcert.sh mineos_console.js service.js webui.js
cp mineos.conf /etc/mineos.conf
npm install
ln -s /usr/games/minecraft/mineos_console.js /usr/local/bin/mineos

# disable webmin
update-rc.d webmin disable

# revert yescrypt to sha512
