#!/bin/sh -ex

# turn off root-login by default
sed -i 's/^PermitRootLogin.*/PermitRootLogin no/' $CHROOT/etc/ssh/sshd_config

# add node14 to apt-get repos
curl -sL https://deb.nodesource.com/setup_14.x | bash -
apt-get -y install nodejs

# add java16
wget https://github.com/AdoptOpenJDK/openjdk16-binaries/releases/download/jdk-16.0.1%2B9/OpenJDK16U-jre_x64_linux_hotspot_16.0.1_9.tar.gz -O openjdk-16-jre.tgz
tar xf openjdk-16-jre.tgz
mv jdk-16.0.* /opt/openjdk-16.0-jre
ln -s /opt/openjdk-16.0-jre/bin/java /usr/bin/java
rm openjdk-16-jre.tgz

# install webui from git
cd /usr/games
git clone --depth=1 https://github.com/hexparrot/mineos-node minecraft
cd minecraft
git config core.filemode false
chmod +x generate-sslcert.sh mineos_console.js service.js webui.js
cp mineos.conf /etc/mineos.conf
npm install
ln -s /usr/games/minecraft/mineos_console.js /usr/local/bin/mineos

# disable webmin
update-rc.d webmin disable
